name: tb_segmentationV4
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - postgresql
  - pip
  - pip:
      - simpleitk
      - pandas
      - scikit-learn
      - pydicom
      - numpy
      - ultralytics==8.2.2
      - dill
      - monai
      - nnunetv2
      - optuna
      - tensorboard

